namespace RecursosHumanos.Shared.Models;

public record Trabajador(
    int CodigoSucursal, 
    int IdTrabajador,
    string ApellidoPaterno,
    string ApellidoMaterno,
    string Nombres,
    string Identificacion,
    string EntidadBancaria,
    string CarnetIESS,
    string Direccion,
    string TelefonoFijo,
    string TelefonoMovil,
    string NumeroCuentaBancaria,
    string CodigoCategoriaOcupacion,
    string Ocupacion,
    string NivelSalarial,
    string TipoComision,
    DateTime FechaNacimiento,
    DateTime FechaIngreso,
    DateTime FechaCese,
    int PeriodoVacaciones,
    DateTime FechaReingreso,
    DateTime FechaUltimaActualizacion,
    int? BancoCTA_CTE,
    int BonificacionComplementaria,
    int BonificacionEspecial,
    int RemuneracionMinima,
    int CuotaCuentaCorriente,
    string FondoReserva,
    string? Mensaje,
    string CodigoCentroCostos = "",
    string CodigoEstadoTrabajador = "",
    string CodigoTipoContrato = "",
    string CodigoTipoCese = "",
    string CodigoEstadoCivil = "",
    string CodigoTipoCuenta = "",
    string CodigoSexo = "");